# Site settings

name: "Martinez Outschoorn Research Group"
description: "Martinez Outschoorn Research Group Site"

url: "http://people.umass.edu/vimartin"
baseurl: "/vimartin"


# Build settings
markdown: rdiscount
permalink: pretty
highlighter: null
excerpt_separator: <!--more-->
encoding: utf-8

gems:
  - jekyll-sitemap
